from __future__ import annotations

import logging
import os
import time
from typing import TYPE_CHECKING, Any

import numpy as np

from infretis.classes.path import DEFAULT_MAXLEN, paste_paths

logger = logging.getLogger(__name__)  # pylint: disable=invalid-name
logger.addHandler(logging.NullHandler())


if TYPE_CHECKING:  # pragma: no cover
    from collections.abc import Callable

    from numpy.random import Generator

    from infretis.classes.engines.enginebase import EngineBase
    from infretis.classes.path import Path as InfPath
    from infretis.classes.system import System

    # Define a signature for move methods:
    MoveMethod = Callable[..., tuple[bool, InfPath, str]]


def log_mdlogs(inp: str) -> None:
    """Log performance metrics from log files in a specified directory.

    Args:
        inp: The directory containing the log files to process.

    Returns:
        None, but if a line containing "Performance" is found,
        this will be logged at the info level.

    """
    logs = [log for log in os.listdir(inp) if "log" in log]
    for log in logs:
        with open(os.path.join(inp, log)) as read:
            for line in read:
                if "Performance" in line:
                    logger.info(
                        log + " " + line.rstrip().split()[1] + " ns/day"
                    )


def run_md(md_items: dict[str, Any]) -> dict[str, Any]:
    """Execute MD simulation step(s).

    Args:
        md_items: Parameters and objects needed by the MD simulation.

    Returns:
        The updated `md_items` dictionary with additional results from
        the MD simulation.
    """
    # record start time
    md_items["wmd_start"] = time.time()

    # perform the hw move:
    picked = md_items["picked"]
    _, trials, status = select_shoot(picked)

    # Record data
    for trial, ens_num in zip(trials, picked.keys()):
        log_mdlogs(picked[ens_num]["engine"].exe_dir)
        md_items["moves"].append(md_items["mc_moves"][ens_num + 1])
        md_items["trial_len"].append(trial.length)
        md_items["trial_op"].append((trial.ordermin[0], trial.ordermax[0]))
        md_items["generated"].append(trial.generated)
        if status == "ACC":
            minus = True if ens_num < 0 else False
            trial.weights = calc_cv_vector(
                trial,
                md_items["interfaces"],
                md_items["mc_moves"],
                cap=md_items["cap"],
                minus=minus,
            )
            picked[ens_num]["traj"] = trial

    md_items.update({"status": status, "wmd_end": time.time()})
    return md_items


def calc_cv_vector(
    path: InfPath,
    interfaces: list[float],
    moves: list[str],
    cap: float | None = None,
    minus: bool = False,
) -> tuple[float, ...]:
    """Calculate weights for the given path.

    Args:
        path: The path to calculate weights for.
        interfaces: The positions of the interfaces.
        moves: The MC moves performed.
        cap: The cap value for the Wire Fencing (wf) move.
        minus: Indicate if the math is a minus path or not.

    Returns:
        The vector of weights for the given path.
    """
    path_max, _ = path.ordermax

    cv = []
    if minus:
        return (1.0 if interfaces[0] <= path_max else 0.0,)

    for idx, intf_i in enumerate(interfaces[:-1]):
        if moves[idx + 1] == "wf":
            intf_cap = cap if cap is not None else interfaces[-1]
            intfs = [interfaces[0], intf_i, intf_cap]
            cv.append(compute_weight(path, intfs, moves[idx + 1]))
        else:
            cv.append(1.0 if intf_i <= path_max else 0.0)
    cv.append(0.0)
    return tuple(cv)


def compute_weight(path: InfPath, interfaces: list[float], move: str) -> float:
    """Compute the High Acceptance path weight after a MC move.

    This function calculates the weights that will be used in the
    computation of the crossing probability. This trick allows the
    use of the High Acceptance version of Stone Skipping (SS) or
    Wire Fencing (WF), allowing the acceptance of B to A paths.
    The drawback is that swapping moves needs to account also
    for this different weights.
    The weight 1 will be returned for a path not generated by SS or WF.

    Args:
        path: The path to be weighted.
        interfaces: A list of three floats representing interface
            positions, in the order `[left, middle, right]`.
        move: A string representing the MC move to compute
            the weights for. Expected values include "ss" for
            Stone Skipping and "wf" for Wire Fencing.

    Returns:
        The weight of the path.
    """
    weight = 1.0

    if move == "wf":
        wf_weight, _ = wirefence_weight_and_pick(
            path, interfaces[1], interfaces[2]
        )
        weight = 1.0 * wf_weight

    if path.get_start_point(
        interfaces[0], interfaces[2]
    ) != path.get_end_point(interfaces[0], interfaces[2]):
        if move in ("ss", "wf"):
            weight *= 2

    return weight


def wirefence_weight_and_pick(
    path: InfPath,
    left: float,
    right: float,
    return_seg: bool = False,
    ens_set: dict[str, Any] | None = None,
) -> tuple[int, InfPath]:
    """Calculate the weight of a path generated by Wire Fencing (WF).

    The WF path weight is determined by the total sum pasepoints in
    valid sub-paths. The valid WF sub-paths are defined by the left
    and right interfaces: `left -> left`, `left -> right`, and
    `right -> left` sub-paths.

    Args:
        path: This is the input path which will be trimmed.
        left: The position of the LEFT interface.
        right: The position of the RIGHT interface.
        return_seg: If True, return a random valid WF sub-path.

    Returns:
        A tuple containing:
            - n_frames: The weight of the path.
            - segment: Return a random valid WF sub-path if `return_seg`
                is True. Otherwise, return an empty path.

    """
    key_l, key_r = False, False
    path_arr = []
    isave = 0

    for i in range(len(path.phasepoints[:-1])):
        op1 = path.phasepoints[i].order[0]
        op2 = path.phasepoints[i + 1].order[0]

        if (op1 < left and op2 >= right) or (op2 < left and op1 >= right):
            pass
        elif op2 >= left > op1 and not key_l:
            isave, key_l = i, True
        elif op2 < right <= op1 and not key_r:
            isave, key_r = i, True
        elif key_r and op2 >= right > op1:
            key_l, key_r = False, False
        elif True in (key_l, key_r) and (
            op2 < left <= op1 or op2 >= right > op1
        ):
            key_l, key_r = False, False
            path_arr.append((isave, i + 1, i - isave))

    n_frames = sum(i[2] for i in path_arr) if path_arr else 0
    if return_seg and n_frames and ens_set is not None:
        sum_frames = 0
        subpath_select = ens_set["rgen"].random()
        for ipath in path_arr:
            sum_frames += ipath[2]
            if sum_frames / n_frames >= subpath_select:
                new_segment = path.empty_path()
                for j in range(ipath[0], ipath[1] + 1):
                    new_segment.append(path.phasepoints[j])
                new_segment.maxlen = path.maxlen
                new_segment.status = path.status
                new_segment.time_origin = path.time_origin
                new_segment.generated = "ct"
                return n_frames, new_segment
    return n_frames, path.empty_path()


def select_shoot(
    picked: dict[int, Any], start_cond: tuple[str, ...] = ("L",)
) -> tuple[bool, list[InfPath], str]:
    """Select shooting move and generate a new path.

    Args:
        picked: A dictionary mapping the ensemble indices to their
            settings, including the move, current path and engine.
        start_cond: The starting condition for the path.
            This is determined by the ensemble we are generating
            for - it is right ("R") or left ("L").

    Returns:
        A tuple containing:
            - True if the new path can be accepted, False otherwise.
            - The generated path.
            - A string representing the status of the path.

    """
    sh_moves: dict[str, MoveMethod] = {
        "wf": wire_fencing,
        "sh": shoot,
    }

    if len(picked) == 1:
        pens = next(iter(picked.values()))
        ens_set, path, engine = (pens[i] for i in ["ens", "traj", "engine"])

        move = ens_set["mc_move"]
        logger.info(
            f"starting {move} in {ens_set['ens_name']}"
            + f" with path_n {path.path_number}"
        )
        start_cond = ens_set["start_cond"]
        accept, new_path, status = sh_moves[move](
            ens_set, path, engine, start_cond=start_cond
        )
        new_paths = [new_path]
    else:
        accept, new_paths, status = retis_swap_zero(picked)

    logger.info(f"Move was {accept} with status {status}\n")
    return accept, new_paths, status


def shoot(
    ens_set: dict[str, Any],
    path: InfPath,
    engine: EngineBase,
    shooting_point: System | None = None,
    start_cond: tuple[str, ...] = ("L",),
) -> tuple[bool, InfPath, str]:
    """Perform a shooting move.

    Args:
        ens_set: Settings for the ensemble.
        path: The initial path to shoot from.
        engine: The MD engine used for generating a new path.
        shooting_point: The selected shooting point. If None,
            it will be randomly selected here.
        start_cond: The starting condition for the ensemble as
            left ("L") or right ("R").

    Returns:
        A tuple containing:
            - True if the new path can be accepted, False otherwise.
            - The generated path.
            - A string representing the status of the path.

    """
    interfaces = ens_set["interfaces"]
    trial_path = path.empty_path()  # The trial path we will generate.
    if shooting_point is None:
        shooting_point, idx, dek = prepare_shooting_point(
            path, ens_set["rgen"], engine
        )
        kick = check_kick(
            shooting_point, interfaces, trial_path, ens_set["rgen"], dek
        )
    else:
        kick = True
        idx = getattr(shooting_point, "idx", 0)

    # Store info about this point, just in case we have to return
    # before completing a full new path:
    trial_path.generated = ("sh", shooting_point.order[0], idx, 0)
    trial_path.time_origin = path.time_origin + idx
    # We now check if the kick was OK or not:
    if not kick:
        return False, trial_path, trial_path.status
    # OK: kick was either aimless or it was accepted by Metropolis
    # We should now generate trajectories, but first check how long
    # it should be (if the path comes from a load, it is assumed to not
    # respect the detail balance anyway):
    if path.get_move() == "ld" or ens_set.get("allowmaxlength", False):
        maxlen = ens_set.get("maxlength", DEFAULT_MAXLEN)
    else:
        maxlen = min(
            int((path.length - 2) / ens_set["rgen"].random()) + 2,
            ens_set.get("maxlength", DEFAULT_MAXLEN),
        )
    # Since the forward path must be at least one step, the maximum
    # length for the backward path is maxlen-1.

    # Generate the backward path:
    path_back = path.empty_path(maxlen=maxlen - 1)
    # todo this inputs are a mess
    # Set ensemble state to the selected shooting point:
    # ensemble['system'] = shooting_point.copy()
    shpt_copy = shooting_point.copy()
    if not shoot_backwards(
        path_back, trial_path, shpt_copy, ens_set, engine, start_cond
    ):
        return False, trial_path, trial_path.status

    # Generate forward path:
    # Note that the length of the forward path is adjusted to
    # account for the fact that it shares a point with the backward
    # path (i.e. the shooting point). The duplicate point is just
    # counted once when the paths are merged by the method
    # `paste_paths` by setting `overlap=True`.
    path_forw = path.empty_path(maxlen=(maxlen - path_back.length + 1))
    logger.debug("Propagating forwards for shooting move...")
    # Set ensemble state to the selected shooting point:
    # change the system state.
    # ensemble['system'] = shooting_point.copy()
    shpt_copy = shooting_point.copy()
    success_forw, _ = engine.propagate(
        path_forw, ens_set, shpt_copy, reverse=False
    )
    path_forw.time_origin = trial_path.time_origin
    # Now, the forward propagation could have failed by exceeding the
    # maximum length for the forward path. However, it could also fail
    # when we paste together so that the length is larger than the
    # allowed maximum. We paste first and ask later:
    trial_path = paste_paths(
        path_back,
        path_forw,
        overlap=True,
        maxlen=ens_set.get("maxlength", DEFAULT_MAXLEN),
    )

    # Also update information about the shooting:
    trial_path.generated = (
        "sh",
        shooting_point.order[0],
        idx,
        path_back.length - 1,
    )
    if not success_forw:
        trial_path.status = "FTL"
        # If we reached this point, the backward path was successful,
        # but the forward was not. For the case where the forward was
        # also successful, the length of the trial path cannot exceed
        # the maximum length given in the TIS settings. Thus we only
        # need to check this here, i.e. when given that the backward
        # was successful and the forward not:
        if trial_path.length == ens_set.get("maxlength", DEFAULT_MAXLEN):
            trial_path.status = "FTX"  # exceeds "memory".
        return False, trial_path, trial_path.status

    trial_path.weight = 1.0

    # Deal with the rejections for path properties.
    # Make sure we did not hit the left interface on {0-}
    # Which is the only ensemble that allows paths starting in R
    if (
        "L" not in set(start_cond)
        and "L" in trial_path.check_interfaces(interfaces)[:2]
    ):
        trial_path.status = "0-L"
        return False, trial_path, trial_path.status

    # Last check - Did we cross the middle interface?
    # Don't do this for paths that can start everywhere
    start_cond = ens_set.get("start_cond", start_cond)
    if set(("R", "L")) == set(start_cond):
        pass
    elif not trial_path.check_interfaces(interfaces)[-1][1]:
        # No, we did not cross the middle interface:
        trial_path.status = "NCR"
        return False, trial_path, trial_path.status

    trial_path.status = "ACC"

    return True, trial_path, trial_path.status


def wire_fencing(
    ens_set: dict[str, Any],
    trial_path: InfPath,
    engine: EngineBase,
    start_cond: tuple[str, ...] = ("L",),
) -> tuple[bool, InfPath, str]:
    """Perform a Wire Fencing move from an initial path.

    Args:
        ens_set: Ensemble settings.
        trial_path: The path to perform the move from.
        engine: The MD engine used for propagating.
        start_cond: The starting condition for the ensemble as
            left ("L") or right ("R").

    Returns:
        A tuple containing:
            - True if the path can be accepted, False otherwise.
            - The generated path.
            - A string representing the status of the path.

    """
    intf_cap = ens_set["tis_set"].get(
        "interface_cap",
        ens_set["interfaces"][2],
    )
    wf_int = list([ens_set["interfaces"][1]] * 2) + [intf_cap]
    n_frames, new_segment = wirefence_weight_and_pick(
        trial_path, wf_int[0], wf_int[2], return_seg=True, ens_set=ens_set
    )

    # Check if no frames to shoot from
    if n_frames == 0:
        logger.warning("Wire fencing move not usable. N frames of Path = 0")
        logger.warning(f"between interfaces {wf_int[0]} and {wf_int[-1]}.")
        return False, trial_path, "NSG"

    sub_ens = {
        "interfaces": wf_int,
        "rgen": ens_set["rgen"],
        "allowmaxlength": True,
        "maxlength": DEFAULT_MAXLEN,
        "ens_name": ens_set["ens_name"],
        "start_cond": ens_set["start_cond"],
    }

    succ_seg = 0
    for i in range(ens_set["tis_set"].get("n_jumps", 2)):
        logger.debug("Trying a new web with Wire Fencing, jump %i", i)
        success, trial_seg, status = shoot(
            sub_ens, new_segment, engine, start_cond=("L", "R")
        )
        start, end, _, _ = trial_seg.check_interfaces(wf_int)
        logger.info(
            f"Jump {i}, len {trial_seg.length}, status"
            + f"{status}, intf: {start} {end}"
        )
        if not success:
            # This handles R to R (start_cond = L) paths. Counter + 1, no ups.
            logger.debug("Wire Fencing Fail.")
        else:
            logger.debug("Acceptable Wire Fence link.")
            succ_seg += 1
            new_segment = trial_seg.copy()
    if succ_seg == 0:
        # No usable segments were generated.
        trial_path.status = "NSG"
        success = False
    else:
        success, trial_path, _ = extender(
            new_segment, engine, ens_set, start_cond
        )
    if success:
        success, trial_path = subt_acceptance(
            trial_path, ens_set, engine, start_cond
        )

    trial_path.generated = ("wf", 9000, succ_seg, trial_path.length)

    logger.debug("WF move %s", trial_path.status)
    if not success:
        return False, trial_path, trial_path.status

    # This might get triggered when accepting 0-L paths.
    left, _, right = ens_set["interfaces"]
    # TODO: check this
    # print(start_cond, tuple(trial_path.get_start_point(left, right)))
    assert set(start_cond) == set(
        trial_path.get_start_point(left, right)
    ), "WF: Path has an implausible start."

    trial_path.status = "ACC"
    return True, trial_path, trial_path.status


def subt_acceptance(
    trial_path: InfPath,
    ens_set: dict[str, Any],
    engine: EngineBase,
    start_cond: tuple[str, ...] = ("L",),
) -> tuple[bool, InfPath]:
    """Process and weight paths generated by Wire Fencing (WF).

    This method will weight and potentially reverse generated paths by
    WF. It will also judge if the path can be accepted or if it should
    be rejected.

    Args:
        trial_path: This is the new path that will obtain weights,
            and might be reversed and accepted.
        ens_set: Ensemble settings.
        engine: The MD engine used for propagating.
        start_cond: The starting condition for the ensemble as
            left ("L") or right ("R").

    Returns:
        A tuple containing:
            - True if the path can be accepted. False otherwise.
            - The weighed and possibly reversed path.

    """
    intf = list(ens_set["interfaces"])
    move = ens_set["mc_move"]

    if move == "wf":
        intf[2] = ens_set["tis_set"].get("interface_cap", intf[2])
    trial_path.weight = compute_weight(trial_path, intf, move)

    if set(start_cond) != set(trial_path.get_start_point(intf[0], intf[2])):
        trial_path = trial_path.reverse(engine.order_function)

    if set(start_cond) != set(trial_path.get_start_point(intf[0], intf[2])):
        trial_path.status = "BWI"
        return False, trial_path
    trial_path.status = "ACC"
    return True, trial_path


def extender(
    source_seg: InfPath,
    engine: EngineBase,
    ens_set: dict[str, Any],
    start_cond: tuple[str, ...] = ("R", "L"),
) -> tuple[bool, InfPath, str]:
    """Extend a path segment backward and forward in time.

    Args:
        source_seg: The path (segment) to extend.
        engine: The MD engine used for propagating.
        ens_set: Ensemble settings.
        start_cond: The starting condition for the ensemble as
            left ("L") or right ("R").

    Returns:
        A tuple containing:
            - True if the path can be accepted, False otherwise.
            - The generated path.
            - A string representing the status of the path.
    """
    interfaces = ens_set["interfaces"]
    # ensemble['system'] = source_seg.phasepoints[0].copy()
    sh_pt = source_seg.phasepoints[0].copy()

    # Extender
    if interfaces[0] <= sh_pt.order[0] < interfaces[-1]:
        back_segment = source_seg.empty_path(
            maxlen=ens_set["tis_set"]["maxlength"]
        )
        logger.debug("Trying to extend backwards")
        source_seg_copy = source_seg.copy()

        shoot_backwards(
            back_segment, source_seg_copy, sh_pt, ens_set, engine, start_cond
        )
        trial_path = paste_paths(
            back_segment,
            source_seg,
            overlap=True,
            maxlen=ens_set["tis_set"]["maxlength"],
        )
    else:
        trial_path = source_seg.copy()

    sh_pt = trial_path.phasepoints[-1].copy()
    if interfaces[0] <= sh_pt.order[0] < interfaces[-1]:
        forth_segment = source_seg.empty_path(
            maxlen=ens_set["tis_set"]["maxlength"]
        )
        engine.propagate(forth_segment, ens_set, sh_pt)

        trial_path.phasepoints = (
            trial_path.phasepoints[:-1] + forth_segment.phasepoints
        )

    if trial_path.length >= ens_set["tis_set"]["maxlength"]:
        trial_path.status = "FTX"  # exceeds "memory".
        return False, trial_path, trial_path.status
    trial_path.status = "ACC"
    return True, trial_path, trial_path.status


def shoot_backwards(
    path_back: InfPath,
    trial_path: InfPath,
    system: System,
    ens_set: dict[str, Any],
    engine: EngineBase,
    start_cond: tuple[str, ...],
) -> bool:
    """Propagate a path in the backward time direction.

    Args:
        path_back: The path to be filled with phase points from the
            propagation.
        trial_path: The current trial path generated by the shooting.
        system: The phase point to shoot from.
        ens_set: Ensemble settings.
        engine: The MD engine used for propagating.
        start_cond: The starting condition for the ensemble as
            left ("L") or right ("R").

    Returns:
        True if the backward path was generated successfully, False
        otherwise.

    """
    logger.debug("Propagating backwards for the shooting move.")
    path_back.time_origin = trial_path.time_origin
    success_back, _ = engine.propagate(
        path_back, ens_set, system, reverse=True
    )
    if not success_back:
        # Something went wrong, most probably the path length was exceeded.
        trial_path.status = "BTL"  # BTL = backward trajectory too long.
        # Add the failed path to trial path for analysis:
        trial_path += path_back
        if path_back.length >= ens_set.get("maxlength", DEFAULT_MAXLEN) - 1:
            # BTX is backward trajectory longer than maximum memory.
            trial_path.status = "BTX"
        return False
    # Backward seems OK so far, check if the ending point is correct:
    left, _, right = ens_set["interfaces"]
    if path_back.get_end_point(left, right) not in set(start_cond):
        # Nope, backward trajectory end at wrong interface.
        trial_path += path_back  # Store path for analysis.
        trial_path.status = "BWI"
        return False
    return True


def prepare_shooting_point(
    path: InfPath, rgen: Generator, engine: EngineBase
) -> tuple[System, int, float]:
    """Select and modify velocities for a shooting move.

    This method will randomly select a shooting point from a given
    path and modify its velocities.

    Args:
        path: This is the input path which will be used for generating a
        new path.
        rgen: A random number generator used for selecting the shooting
            point from the path.
        engine: The MD engine used for generating velocities.

    Returns:
        A tuple containing:
            - The shooting point with modified velocities.
            - The index of the shooting point in the original path.
            - The change in kinetic energy when modifying the velocities.

    """
    shooting_point, idx = path.get_shooting_point(rgen)
    orderp = shooting_point.order
    shpt_copy = shooting_point.copy()
    logger.info("Shooting from order parameter/index: %f, %d", orderp[0], idx)
    # Copy the shooting point, so that we can modify velocities without
    # altering the original path:
    # Modify the velocities:
    (
        dek,
        _,
    ) = engine.modify_velocities(
        shpt_copy,
        {
            "sigma_v": False,
            "aimless": True,
            "zero_momentum": True,
            "rescale": False,
        },
    )
    orderp = engine.calculate_order(shpt_copy)
    shpt_copy.order = orderp
    return shpt_copy, idx, dek


def check_kick(
    shooting_point: System,
    interfaces: list[float],
    trial_path: InfPath,
    rgen: Generator,
    dek: float,
    aimless: bool = True,
) -> bool:
    """Check the modification of the shooting point.

    After generating velocities for a shooting point, we
    do some additional checking to see if the shooting point is
    acceptable.

    Args:
        shooting_point: The shooting point with modified velocities.
        interfaces: The interfaces on the form `[left, middle, right]`.
        trial_path: The path we are currently generating.
        rgen: A random generator used to check if we accept the
            shooting point based on the change in kinetic energy.
        dek: The change in kinetic energy when modifying the velocities.
        aimless: Specifies if the shooting is aimless (True).

    Returns:
        True if the modification was acceptable.

    """
    # 1) Check if the kick was too violent:
    left, _, right = interfaces
    if not left <= shooting_point.order[0] < right:
        # Shooting point was velocity dependent and was kicked outside
        # of boundaries when modifying velocities.
        trial_path.append(shooting_point)
        trial_path.status = "KOB"
        return False
    # 2) If the kick is not aimless, we check if we reject it or not:
    if not aimless:
        accept_kick = metropolis_accept_reject(rgen, shooting_point, dek)
        # If one wish to implement a bias call, this can be done here.
        if not accept_kick:
            trial_path.append(shooting_point)
            trial_path.status = "MCR"  # Momenta Change Rejection.
            return False
    return True


def retis_swap_zero(
    picked: dict[int, Any],
) -> tuple[bool, list[InfPath], str]:
    """Perform the RETIS swapping for `[0^-] <-> [0^+]` swaps.

    Args:
        picked: A dictionary mapping the ensemble indices to their
            settings, including the move, current path and engine.

    Returns:
        A tuple containing:
            - True if the path can be accepted, False otherwise.
            - The generated paths.
            - A string representing the status of the paths.

    Note:
        The swapping move for ensembles [0^-] and [0^+] requires some
        extra propagation. Here we are generating new paths for [0^-]
        and [0^+] in the following way:

        1) For [0^-] we take the initial point in [0^+] and integrate
           backward in time. This is merged with the second point in [0^+]
           to give the final path. The initial point in [0^+] starts to the
           left of the interface and the second point is on the right
           side - i.e., the path will cross the interface at the end points.
           If we let the last point in [0^+] be called `A_0` and the
           second last point `B`, and we let `A_1, A_2, ...` be the
           points on the backward trajectory generated from `A_0` then
           the final path will be made up of the points
           `[..., A_2, A_1, A_0, B]`. Here, `B` will be on the right
           side of the interface and the first point of the path will also
           be on the right side.

        2) For [0^+] we take the last point of [0^-] and use that as an
           initial point to generate a new trajectory for [0^+] by
           integration forward in time. We also include the second last
           point of the [0^-] trajectory which is on the left side of the
           interface. We let the second last point be `B` (this is on the
           left side of the interface), the last point `A_0` and the
           points generated from `A_0` we denote by `A_1, A_2, ...`.
           Then the resulting path will be `[B, A_0, A_1, A_2, ...]`.
           Here, `B` will be on the left side of the interface and the
           last point of the path will also be on the left side of the
           interface.

    """
    ens_set0 = picked[-1]["ens"]
    ens_set1 = picked[0]["ens"]
    engine0 = picked[-1]["engine"]
    engine1 = picked[0]["engine"]
    path_old0 = picked[-1]["traj"]
    path_old1 = picked[0]["traj"]
    maxlen0 = ens_set0.get("maxlength", DEFAULT_MAXLEN)
    maxlen1 = ens_set1.get("maxlength", DEFAULT_MAXLEN)

    ens_moves = [ens_set0["mc_move"], ens_set1["mc_move"]]
    intf_w = [list(ens_set0["interfaces"]), list(ens_set1["interfaces"])]

    # intf_w = [list(i) for i in (path_ensemble0.interfaces,
    #                             path_ensemble1.interfaces)]
    for i, mc_move in enumerate([ens_set0["tis_set"], ens_set1["tis_set"]]):
        intf_w[i][2] = mc_move.get("interface_cap", intf_w[i][2])

    # for i, j in enumerate([settings['ensemble'][k] for k in (0, 1)]):
    #     if ens_moves[i] == 'wf':
    #         intf_w[i][2] = j['tis'].get('interface_cap', intf_w[i][2])

    # 0. check if MD is allowed
    # allowed = (path_ensemble0.last_path.get_end_point(
    #             path_ensemble0.interfaces[0],
    #             path_ensemble0.interfaces[-1]) == 'R')
    allowed = (
        path_old0.get_end_point(
            ens_set0["interfaces"][0], ens_set0["interfaces"][-1]
        )
        == "R"
    )
    # if allowed:
    #     swap_ensemble_attributes(ensemble0, ensemble1, settings)

    # 1. Generate path for [0^-] from [0^+]:
    # We generate from the first point of the path in [0^+]:
    logger.debug("Swapping [0^-] <-> [0^+]")
    logger.debug("Creating path for [0^-]")
    # system = path_ensemble1.last_path.phasepoints[0].copy()
    shpt_copy = path_old1.phasepoints[0].copy()
    # shpt_copy2 = path_old1.phasepoints[0].copy()
    logger.debug("Initial point is: %s", shpt_copy)
    # Propagate it backward in time:
    path_tmp = path_old1.empty_path(maxlen=maxlen1 - 1)
    if allowed:
        logger.debug("Propagating for [0^-]")
        engine0.propagate(path_tmp, ens_set0, shpt_copy, reverse=True)
    else:
        logger.debug("Not propagating for [0^-]")
        path_tmp.append(shpt_copy)
    path0 = path_tmp.empty_path(maxlen=maxlen0)
    for phasepoint in reversed(path_tmp.phasepoints):
        path0.append(phasepoint)
    # print('lobster a', path_tmp.length, path0.length, allowed)
    # Add second point from [0^+] at the end:
    logger.debug("Adding second point from [0^+]:")
    # Here we make a copy of the phase point, as we will update
    # the configuration and append it to the new path:
    # phase_point = path_ensemble1.last_path.phasepoints[1].copy()
    phase_point = path_old1.phasepoints[1].copy()
    logger.debug("Point is %s", phase_point)
    engine1.dump_phasepoint(phase_point, "second")
    path0.append(phase_point)
    if path0.length == maxlen0:
        path0.status = "BTX"
    elif path0.length < 3:
        path0.status = "BTS"
    elif (
        "L" not in set(ens_set0["start_cond"])
        and "L" in path0.check_interfaces(ens_set0["interfaces"])[:2]
    ):
        path0.status = "0-L"
    else:
        path0.status = "ACC"
    # print(path0.status)

    # 2. Generate path for [0^+] from [0^-]:
    logger.debug("Creating path for [0^+] from [0^-]")
    # This path will be generated starting from the LAST point of [0^-] which
    # should be on the right side of the interface. We will also add the
    # SECOND LAST point from [0^-] which should be on the left side of the
    # interface, this is added after we have generated the path and we
    # save space for this point by letting maxlen = maxlen1-1 here:
    path_tmp = path0.empty_path(maxlen=maxlen1 - 1)
    # We start the generation from the LAST point:
    # Again, the copy below is not needed as the propagate
    # method will not alter the initial state.
    # system = path_ensemble0.last_path.phasepoints[-1].copy()
    system = path_old0.phasepoints[-1].copy()
    if allowed:
        logger.debug("Initial point is %s", system)
        # nsembles[1]['system'] = system
        logger.debug("Propagating for [0^+]")
        engine1.propagate(path_tmp, ens_set1, system, reverse=False)
        # Ok, now we need to just add the SECOND LAST point from [0^-] as
        # the first point for the path:
        path1 = path_tmp.empty_path(maxlen=maxlen1)
        # phase_point = path_ensemble0.last_path.phasepoints[-2].copy()
        phase_point = path_old0.phasepoints[-2].copy()
        logger.debug("Add second last point: %s", phase_point)
        engine0.dump_phasepoint(phase_point, "second_last")
        path1.append(phase_point)
        path1 += path_tmp  # Add rest of the path.
    else:
        path1 = path_tmp
        path1.append(system)
        logger.debug("Skipping propagating for [0^+] from L")

    ##### NB if path_ensemble1.last_path.get_move() != 'ld':
    ##### NB     path0.set_move('s+')
    ##### NB else:
    ##### NB     path0.set_move('ld')

    ##### NB if path_ensemble0.last_path.get_move() != 'ld':
    ##### NB     path1.set_move('s-')
    ##### NB else:
    ##### NB     path1.set_move('ld')
    if path1.length >= maxlen1:
        path1.status = "FTX"
    elif path1.length < 3:
        path1.status = "FTS"
    else:
        path1.status = "ACC"
    logger.debug("Done with swap zero!")

    # Final checks:
    accept = path0.status == "ACC" and path1.status == "ACC"
    status = (
        "ACC"
        if accept
        else (path0.status if path0.status != "ACC" else path1.status)
    )
    # High Acceptance swap is required when Wire Fencing are used
    if accept:
        if "wf" in ens_moves:
            accept, status = high_acc_swap(
                [path1, path_old1],
                ens_set0["rgen"],
                intf_w[0],
                intf_w[1],
                ens_moves,
            )

    for i, path, _, _ in (
        (0, path0, ens_set0["tis_set"], "s+"),
        (1, path1, ens_set1["tis_set"], "s-"),
    ):
        if not accept and path.status == "ACC":
            path.status = status

        # These should be 1 unless length of paths equals 3.
        # This technicality is not yet fixed. (An issue is open as a reminder)

        # ens_set = settings['ensemble'][i]
        move = ens_moves[i]
        path.weight = (
            compute_weight(path, intf_w[i], move) if move in ("wf") else 1
        )

    return accept, [path0, path1], status


def metropolis_accept_reject(
    rgen: Generator, system: System, deltae: float
) -> bool:
    """Accept/reject a change in energy according to the metropolis rule.

    Args:
        rgen: The random number generator.
        system: The system object we are investigating
            This is used to access the beta factor.
        deltae: The change in energy.

    Returns:
        True if the move is accepted, False otherwise.

    """
    if deltae < 0.0:  # short-cut to avoid calculating np.exp()
        return True
    pacc = np.exp(-system.temperature["beta"] * deltae)
    return rgen.random() < pacc


def high_acc_swap(
    paths: list[InfPath],
    rgen: Generator,
    intf0: list[float],
    intf1: list[float],
    ens_moves: list[str],
) -> tuple[bool, str]:
    """Accept/reject a swap move using the High Acceptance weights.

    Args:
        paths: The path in the LOWER and UPPER ensemble to exchange.
        rgen: The random number generator.
        intf0: The interfaces of the LOWER ensemble.
        intf1: The interfaces of the HIGHER ensemble.
        ens_moves: The moves used in the two ensembles.

    Returns:
        A tuple containing:
            - True if the move is accepted, False otherwise.
            - A string with the status of acceptance.


    Notes:
        -  This function is only needed when paths are generated via
            Wire Fencing or Stone Skipping.

    """
    # Crossing before the move
    c1_old = compute_weight(paths[0], intf0, ens_moves[0])
    c2_old = compute_weight(paths[1], intf1, ens_moves[1])
    # Crossing if the move would be accepted
    c1_new = compute_weight(paths[1], intf0, ens_moves[0])
    c2_new = compute_weight(paths[0], intf1, ens_moves[1])
    if c1_old == 0 or c2_old == 0:
        logger.warning(
            "div_by_zero. c1_old, c2_old, ens_moves: [%i,%i], %s",
            c1_old,
            c2_old,
            str(ens_moves),
        )
        p_swap_acc = 1.0
    else:
        p_swap_acc = c1_new * c2_new / (c1_old * c2_old)

    # Finally, randomly decide to accept or not:
    if rgen.random() < p_swap_acc:
        return True, "ACC"  # Accepted

    return False, "HAS"  # Rejected
