# infretis config
[runner]
workers = 1
wmdrun = ['gmx mdrun -ntomp 1 -ntmpi 1 -pinoffset 0 -pin on',
	  'gmx mdrun -ntomp 1 -ntmpi 1 -pinoffset 1 -pin on',
	  'gmx mdrun -ntomp 1 -ntmpi 1 -pinoffset 2 -pin on',
	  'gmx mdrun -ntomp 1 -ntmpi 1 -pinoffset 3 -pin on',]

[simulation]
interfaces = [0.345, 0.3625, 1.200]
steps = 10
seed = 0
load_dir = 'load'
shooting_moves = ['sh','sh','wf','wf','wf','wf','wf','wf','wf','wf']
ensemble_engines = [["engine0"],["engine1"],["engine1", "engine2"]] # wf/sh picks only first of these

[simulation.tis_set]
maxlength = 2000
allowmaxlength = false
zero_momentum = true
n_jumps = 3
interface_cap = 0.54
multi_engine = true # define 1 engine in each ensemble

[orderparameter]
class = 'Distance'
index = [ 0, 1]
periodic = true

[output]
data_dir = "./"
screen = 1
pattern = 1
# keep files such as '001_1234_trajF.xtc' and .edr. For .xtc,
# we also need to set 'nstxout-compressed' in the .mdp.
keep_traj_fnames = [".xtc", ".edr"]
delete_old = true # but keeps 'keep_traj_fnames' that match

# Rest is a long engine list
[engine0]
class = 'gromacs'
engine = 'gmx'
timestep = 0.0002
gmx_format = 'g96'
input_path = '../H2/gromacs_input'
gmx = 'gmx'
subcycles = 10
temperature = 300
infretis_genvel = true
masses = [1.008, 1.008]

[engine1]
class = 'gromacs'
engine = 'gmx'
timestep = 0.0002
gmx_format = 'g96'
input_path = '../H2/gromacs_input'
gmx = 'gmx'
subcycles = 10
temperature = 300
infretis_genvel = true
masses = [1.008, 1.008]

[engine2]
class = 'gromacs'
engine = 'gmx'
timestep = 0.0002
gmx_format = 'g96'
input_path = '../H2/gromacs_input'
gmx = 'gmx'
subcycles = 10
temperature = 300
infretis_genvel = true
masses = [1.008, 1.008]
