[infinit]
pL = 0.3
steps_per_iter = [20,40,80,160,320]
nskip = 10
cstep = -1
initial_conf = "initial.traj"
lamres = 0.005

[runner]
workers = 1
wmdrun = [ 1,]

[simulation]
interfaces = [3.45, 12.0]
steps = 10000
seed = 0
load_dir = "load"
shooting_moves = ["sh", "sh"]

[simulation.tis_set]
maxlength = 20000
allowmaxlength = false
zero_momentum = true
n_jumps = 2

[engine]
class = "ase"
engine = "ase"
input_path = "."
temperature = 300
timestep = 0.5
subcycles = 1
integrator = "langevin"
langevin_fixcm = false
langevin_friction = 0.1

[engine.calculator_settings]
module = "H2-calc.py"
class = "LennardJonesCalc"
sigma = 3.0
epsilon = 0.25910675  # 25.0*0.01036427 kj/mol -> eV
rc = 12.0
smooth = false

[orderparameter]
class = "Distance"
index = [0,1]
periodic = true

[output]
data_dir = "./"
screen = 1
pattern = false
delete_old = false
delete_old_all = false
