# infretis config

[runner]
workers = 1
wmdrun = ["0","0"]

[simulation]
interfaces = [0.345, 0.3625, 0.3777, 0.3922, 0.4068, 0.4224, 0.4399, 0.4612, 0.4915, 1.200]
steps = 2
seed = 1
load_dir = 'load'
shooting_moves = ['sh', 'sh', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf']

[simulation.tis_set]
maxlength = 2000
allowmaxlength = false
zero_momentum = true # momentum true
n_jumps = 3
interface_cap = 0.54
quantis = true

[engine1]
class = 'turtlemd'
engine = 'turtlemd'
timestep = 0.0002
temperature = 300
boltzmann = 0.0083144621 # kJ/(K*mol)
subcycles = 10

[engine1.integrator]
class = 'LangevinInertia'
[engine1.integrator.settings]
gamma = 10
beta = 0.4009078751268027 # 1/(boltzmann*T)

[engine1.potential]
class = 'LennardJones'
[engine1.potential.settings]
parameters = {1={"sigma"=0.3, "epsilon"= 25.0, "rcut"= 1.2}}

[engine1.particles]
mass = [1.008, 1.008]
name = ['H', 'H']
pos = [[0.0, 0.0, 0.0], [0.4, 0.0, 0.0]]

[engine1.box]
periodic = [true, true, true]
low = [0, 0, 0]
high = [3, 3, 3]

# engine [N+]
[engine0]
class = 'turtlemd'
engine = 'turtlemd'
timestep = 0.0002
temperature = 300
boltzmann = 0.0083144621 # kJ/(K*mol)
subcycles = 10

[engine0.integrator]
class = 'LangevinInertia'
[engine0.integrator.settings]
gamma = 10
beta = 0.4009078751268027 # 1/(boltzmann*T)

[engine0.potential]
class = 'DoubleWellPair'
[engine0.potential.settings]
parameters = {"rzero"=0.3367, "height"= 25.0, "width"= 0.13}

[engine0.particles]
mass = [1.008, 1.008]
name = ['H', 'H']
pos = [[0.0, 0.0, 0.0], [0.4, 0.0, 0.0]]

[engine0.box]
periodic = [true, true, true]
low = [0, 0, 0]
high = [3, 3, 3]

[orderparameter]
class = 'Distance'
index = [0, 1]
periodic = true

[output]
data_dir = "./" # where to store infretis_data.txt
screen = 1 # how often to print to sim.log
pattern = false # how often we print info of which worker is in which ensemble at any time to pattern.txt
delete_old = true # delete old accepted trajectories (e.g. .trr or .xyz files)
