# infretis config

[dask]
workers = 2
wmdrun = ['gmx mdrun -ntomp 1 -ntmpi 1 -pinoffset 0 -pin on',
	  'gmx mdrun -ntomp 1 -ntmpi 1 -pinoffset 1 -pin on',]

[simulation]
interfaces = [-1.1, -1.0, -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, 0.0, 0.1, 0.2, 1.5]
steps = 100
seed = 0
load_dir = 'load'
shooting_moves = ['sh', 'sh', 'sh', 'sh', 'sh', 'sh', 'sh', 'sh', 'sh', 'sh', 'sh', 'sh', 'sh', 'sh', 'sh']


[simulation.tis_set]
maxlength = 20000
aimless = true
allowmaxlength = false
zero_momentum = true # momentum true
rescale_energy = false
temperature = 300
high_accept = true
n_jumps = 4


[engine]
class = 'gromacs'
engine = 'gmx'
mdrun = 'gmx'
gmx_format = 'g96'
timestep = 0.0005
input_path = 'gromacs_input'
gmx = 'gmx'
subcycles = 10

[orderparameter]
class = 'Dihedral'
index = [ 0, 1, 2, 3]
periodic = true

[output]
backup = 'backup'
data_dir = "./"
order-file = 1
energy-file = 1
trajectory-file = -1
screen = 1
pattern = false
