# infretis config

[dask]
workers = 4
files=["orderp.py"]
wmdrun = ['not used',
	  'not used',
	  'not used',
	  'not used',
	  'not used',
	  'not used',
	  'not used',
	  'not used',]

[simulation]
interfaces = [-0.99, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, 1.0]
steps = 50
seed = 0
load_dir = 'load'
shooting_moves = ['sh','sh','wf','wf','wf','wf','wf','wf']


[simulation.tis_set]
maxlength = 2000
allowmaxlength = false
zero_momentum = false # momentum true
n_jumps = 4


[engine]
class = 'turtlemd'
engine = 'turtlemd'
timestep = 0.025
temperature = 0.07
boltzmann = 1.0
subcycles = 1

[engine.integrator]
class = 'LangevinInertia'
[engine.integrator.settings]
gamma = 0.3
beta = 14.285714285714285 # 1/(boltzmann*T)

[engine.potential]
class = 'DoubleWell'
[engine.potential.settings]
a = 1.0
b = 2.0
c = 0.0

[engine.particles]
mass = [1.0]
name = ['Z']
pos = [[-1.0]]

[engine.box]
periodic = [false]

[orderparameter]
class = 'PositionX'
index = [0, 0] # x-component of first particle
periodic = false
module = 'orderp.py'

[output]
data_dir = "./" # where to store infretis_data.txt
screen = 1 # how often to print to sim.log
pattern = false # how often we print info of which worker is in which ensemble at any time to pattern.txt
delete_old = true # delete old accepted trajectories (e.g. .trr or .xyz files)
