# infretis config

[runner]
workers = 1
wmdrun = [0, 0, 0, 0]

[simulation]
interfaces = [ 3.45, 3.625, 3.777, 3.922, 4.068, 4.224, 4.399, 4.612, 4.915, 12.0]
steps = 100
seed = 0
load_dir = 'load'
shooting_moves = ['sh','sh', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf']


[simulation.tis_set]
maxlength = 2000
allowmaxlength = false
zero_momentum = true # we do not remove momentum by default in lammps
n_jumps = 3
interface_cap = 5.4

[engine]
class = 'cp2k'
engine = 'cp2k'
input_path = 'cp2k_input'
cp2k = 'cp2k.ssmp'
timestep = 0.2
subcycles = 10
temperature = 300

[orderparameter]
class = 'Distance'
index = [0, 1]
periodic = true

[output]
data_dir = "./" # where to store infretis_data.txt
screen = 1 # how often to print to sim.log
pattern = false # how often we print info of which worker is in which ensemble at any time to pattern.txt
delete_old = true # delete old accepted trajectories (e.g. .trr or .xyz files)
keep_traj_fnames = ["-frc-1.xyz"] # keep forces if printed
