# infretis config

[dask]
workers = 4
wmdrun = ['0',
	  '0',
	  '0',
	  '0',]

[simulation]
interfaces = [ 3.45, 3.625, 3.777, 3.922, 4.068, 4.224, 4.399, 4.612, 4.915, 12.0]
steps = 1000
seed = 0
load_dir = 'load'
shooting_moves = ['sh','sh', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf']


[simulation.tis_set]
maxlength = 2000
allowmaxlength = false
zero_momentum = true # we do not remove momentum by default in lammps
n_jumps = 3
interface_cap = 5.4
temperature = 300

[engine]
class = 'cp2k'
engine = 'cp2k'
input_path = 'cp2k_input'
cp2k = 'cp2k.ssmp'
timestep = 0.2
subcycles = 10

[orderparameter]
class = 'Distance'
index = [0, 1]
periodic = true

[output]
backup = 'backup'
data_dir = "./"
order-file = 1
energy-file = 1
trajectory-file = 1
screen = 1
pattern = false
delete_old = false
