# infretis config

[dask]
workers = 8
wmdrun = ['not used',
	  'not used',
	  'not used',
	  'not used',
	  'not used',
	  'not used',
	  'not used',
	  'not used',]

[simulation]
interfaces = [-4.0, -3.7143, -3.4286, -3.1429, -2.8571, -2.5714, -2.2857, -2.0, -1.7143, -1.4286, -1.1429, -0.8571, -0.5714, -0.2857, 0.0, 4.0 ]
steps = 1000
seed = 0
load_dir = 'load'
shooting_moves = ['sh','sh','sh','sh','sh','sh','sh','sh','sh','sh','sh','sh','sh','sh','sh','sh']


[simulation.tis_set]
maxlength = 2000
aimless = true
allowmaxlength = false
zero_momentum = true # momentum true
rescale_energy = false
beta = 2.5
gamma = 2.5


[engine]
class = 'turtlemd'
engine = 'turtlemd'
turtlemd = 'not used'
input_path = 'not used'
timestep = 0.1
mdrun = 'not used'
subcycles = 1

[orderparameter]
class = 'Position'
index = [0, 0] # x-component of first particle
periodic = false

[output]
backup = 'backup'
data_dir = "./"
order-file = 1
energy-file = 1
trajectory-file = -1
screen = 1
pattern = 1
