"""Reducer-facing semantic view context.

``ViewCtx`` is the typed contract that says which semantic carrier,
selectors, weighting convention, summaries/operators, and reductions are
admissible for a reduction workflow. It does not own replay parsing,
math-core measures, partition operators, controller logic, or operator
geometry; it only generates and validates the semantic universe in which
reducers are allowed to run.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any

from infretis.math_core.predicates.ensembles import (
    EnsembleDescriptor,
    EnsembleFiberDescriptor,
    EnsemblePredicateContext,
)
from infretis.syntax_and_context import (
    LEFT_INTERVAL_MASS_V1,
    ReductionContext,
    VersionedTimeWeightPolicy,
)


STANDARD_REDUCTION_VIEW_V1 = "standard_reduction_view_v1"
OBSERVED_PATH_SEMANTICS_V1 = "observed_path_semantics_v1"


class PrimitiveFamily(str, Enum):
    """Primitive semantic carrier generated by a view."""

    ACCEPTED_OBSERVED_PATHS = "accepted_observed_paths_v1"


class ViewSelectorKind(str, Enum):
    """Selector kinds generated by a view."""

    ALL_ACCEPTED = "all_accepted_paths_v1"
    BROAD_ENSEMBLE = "broad_ensemble_membership_v1"
    EXACT_RANK_FIBER = "exact_rank_fiber_v1"


class ViewReductionKind(str, Enum):
    """Reducer-core reductions governed by ``ViewCtx``."""

    R4_NU_E = "r4_nu_e_v1"
    R4B_FAMILY_OPERATOR_PROFILE = "r4b_family_operator_profile_v1"


class ViewSummaryKind(str, Enum):
    """Summary/operator surfaces admissible in the standard R4 view."""

    SCALAR_INTERVAL_BINS = "scalar_interval_bins_v1"
    FAMILY_PARTITIONED_NU_E = "family_partitioned_nu_e_v1"
    TAIL_OPERATOR = "tail_operator_v1"
    UPWARD_CUT_OPERATOR = "upward_cut_operator_v1"
    CUT_PROFILE_OPERATOR = "cut_profile_operator_v1"


@dataclass(frozen=True)
class ObservationSemantics:
    """Resolved observation semantics used by reducer-core views."""

    reduction_context: ReductionContext
    cv_classification: tuple[tuple[str, str], ...]
    reduction_clock: str
    observation_semantics_id: str = OBSERVED_PATH_SEMANTICS_V1

    @classmethod
    def from_reduction_context(
        cls,
        reduction_context: ReductionContext,
    ) -> "ObservationSemantics":
        return cls(
            reduction_context=reduction_context,
            cv_classification=tuple(
                sorted(
                    (str(key), str(value))
                    for key, value in (
                        reduction_context.cv_classification.items()
                    )
                )
            ),
            reduction_clock=reduction_context.reduction_clock,
        )


@dataclass(frozen=True)
class ViewSelector:
    """Typed selector descriptor generated by ``ViewCtx``."""

    selector_kind: ViewSelectorKind
    cv_key: str = "order_parameter"
    ensemble_descriptor: EnsembleDescriptor | None = None
    fiber_descriptor: EnsembleFiberDescriptor | None = None
    predicate_context: EnsemblePredicateContext | None = None

    def __post_init__(self) -> None:
        if not isinstance(self.selector_kind, ViewSelectorKind):
            object.__setattr__(
                self,
                "selector_kind",
                ViewSelectorKind(str(self.selector_kind)),
            )


@dataclass(frozen=True)
class ViewCtx:
    """Resolved semantic/view context for reducer-core workflows."""

    view_id: str
    primitive_family: PrimitiveFamily
    predicate_context: EnsemblePredicateContext | None
    observation_semantics: ObservationSemantics
    time_weight_policy: VersionedTimeWeightPolicy
    allowed_reductions: tuple[ViewReductionKind, ...]
    allowed_selector_kinds: tuple[ViewSelectorKind, ...] = field(
        default_factory=tuple
    )
    allowed_summary_kinds: tuple[ViewSummaryKind, ...] = field(
        default_factory=tuple
    )

    def __post_init__(self) -> None:
        object.__setattr__(
            self,
            "primitive_family",
            self._coerce_primitive_family(self.primitive_family),
        )
        object.__setattr__(
            self,
            "allowed_reductions",
            tuple(
                self._coerce_reduction_kind(item)
                for item in self.allowed_reductions
            ),
        )
        selectors = self.allowed_selector_kinds or self._default_selectors(
            self.primitive_family
        )
        object.__setattr__(
            self,
            "allowed_selector_kinds",
            tuple(self._coerce_selector_kind(item) for item in selectors),
        )
        summaries = self.allowed_summary_kinds or self._default_summaries()
        object.__setattr__(
            self,
            "allowed_summary_kinds",
            tuple(self._coerce_summary_kind(item) for item in summaries),
        )
        context_policy = self.observation_semantics.reduction_context
        if context_policy.time_weight_policy.version != (
            self.time_weight_policy.version
        ):
            raise ValueError(
                "ViewCtx time_weight_policy must match observation semantics"
            )
        self.validate_weighting_contract()

    @classmethod
    def standard_observed_path_view(
        cls,
        reduction_context: ReductionContext,
        *,
        predicate_context: EnsemblePredicateContext | None = None,
        view_id: str = STANDARD_REDUCTION_VIEW_V1,
        primitive_family: PrimitiveFamily = (
            PrimitiveFamily.ACCEPTED_OBSERVED_PATHS
        ),
        allowed_reductions: tuple[ViewReductionKind, ...] | None = None,
    ) -> "ViewCtx":
        """Build the standard R4/R4b view over accepted observed paths."""
        return cls(
            view_id=view_id,
            primitive_family=primitive_family,
            predicate_context=predicate_context,
            observation_semantics=ObservationSemantics.from_reduction_context(
                reduction_context
            ),
            time_weight_policy=reduction_context.time_weight_policy,
            allowed_reductions=allowed_reductions
            or (
                ViewReductionKind.R4_NU_E,
                ViewReductionKind.R4B_FAMILY_OPERATOR_PROFILE,
            ),
        )

    @property
    def reduction_context(self) -> ReductionContext:
        """Resolved context used to build/validate ``ObservedPath`` objects."""
        return self.observation_semantics.reduction_context

    def carrier(self) -> PrimitiveFamily:
        return self.primitive_family

    def selectors(self) -> tuple[ViewSelectorKind, ...]:
        return self.allowed_selector_kinds

    def weights(self) -> tuple[str, ...]:
        return (self.time_weight_policy.version,)

    def summaries(self) -> tuple[ViewSummaryKind, ...]:
        return self.allowed_summary_kinds

    def reductions(self) -> tuple[ViewReductionKind, ...]:
        return self.allowed_reductions

    def validate_reduction(
        self,
        reduction: ViewReductionKind | str,
    ) -> ViewReductionKind:
        reduction_kind = self._coerce_reduction_kind(reduction)
        if reduction_kind not in self.allowed_reductions:
            raise ValueError(
                f"reduction {reduction_kind.value!r} is not allowed for "
                f"view {self.view_id!r}"
            )
        self.validate_weighting_contract()
        return reduction_kind

    def validate_selector_kind(
        self,
        selector_kind: ViewSelectorKind | str,
    ) -> ViewSelectorKind:
        kind = self._coerce_selector_kind(selector_kind)
        if kind not in self.allowed_selector_kinds:
            raise ValueError(
                f"selector {kind.value!r} is not allowed for "
                f"primitive family {self.primitive_family.value!r}"
            )
        return kind

    def validate_selector(self, selector: ViewSelector) -> ViewSelector:
        kind = self.validate_selector_kind(selector.selector_kind)
        if kind is ViewSelectorKind.ALL_ACCEPTED:
            return selector
        if selector.predicate_context is not None:
            if selector.predicate_context is not self.predicate_context:
                raise ValueError(
                    "selector predicate_context is outside this ViewCtx"
                )
        if self.predicate_context is None:
            raise ValueError(
                f"selector {kind.value!r} requires ViewCtx.predicate_context"
            )
        if kind is ViewSelectorKind.BROAD_ENSEMBLE:
            if selector.ensemble_descriptor is None:
                raise ValueError(
                    "broad ensemble selector requires ensemble_descriptor"
                )
        if kind is ViewSelectorKind.EXACT_RANK_FIBER:
            if selector.fiber_descriptor is None:
                raise ValueError(
                    "exact-rank fiber selector requires fiber_descriptor"
                )
        return selector

    def validate_weighting_contract(self) -> None:
        if self.time_weight_policy.version != LEFT_INTERVAL_MASS_V1.version:
            raise ValueError(
                "ViewCtx supports R4/R4b only with time_weight_policy "
                f"{LEFT_INTERVAL_MASS_V1.version!r}; got "
                f"{self.time_weight_policy.version!r}"
            )

    def validate_summary(
        self,
        summary: ViewSummaryKind | str,
    ) -> ViewSummaryKind:
        summary_kind = self._coerce_summary_kind(summary)
        if summary_kind not in self.allowed_summary_kinds:
            raise ValueError(
                f"summary/operator {summary_kind.value!r} is not allowed "
                f"for view {self.view_id!r}"
            )
        return summary_kind

    def default_selector(
        self,
        *,
        cv_key: str = "order_parameter",
    ) -> ViewSelector:
        """Return the standard full-carrier selector: all accepted paths."""
        selector = ViewSelector(
            selector_kind=ViewSelectorKind.ALL_ACCEPTED,
            cv_key=cv_key,
        )
        return self.validate_selector(selector)

    def broad_ensemble_selector(
        self,
        descriptor: EnsembleDescriptor,
        *,
        cv_key: str = "order_parameter",
    ) -> ViewSelector:
        selector = ViewSelector(
            selector_kind=ViewSelectorKind.BROAD_ENSEMBLE,
            cv_key=cv_key,
            ensemble_descriptor=descriptor,
            predicate_context=self.predicate_context,
        )
        return self.validate_selector(selector)

    def exact_rank_fiber_selector(
        self,
        descriptor: EnsembleFiberDescriptor,
        *,
        cv_key: str = "order_parameter",
    ) -> ViewSelector:
        selector = ViewSelector(
            selector_kind=ViewSelectorKind.EXACT_RANK_FIBER,
            cv_key=cv_key,
            fiber_descriptor=descriptor,
            predicate_context=self.predicate_context,
        )
        return self.validate_selector(selector)

    @staticmethod
    def _coerce_primitive_family(
        value: PrimitiveFamily | str,
    ) -> PrimitiveFamily:
        if isinstance(value, PrimitiveFamily):
            return value
        return PrimitiveFamily(value)

    @staticmethod
    def _coerce_selector_kind(
        value: ViewSelectorKind | str,
    ) -> ViewSelectorKind:
        if isinstance(value, ViewSelectorKind):
            return value
        return ViewSelectorKind(value)

    @staticmethod
    def _coerce_reduction_kind(
        value: ViewReductionKind | str,
    ) -> ViewReductionKind:
        if isinstance(value, ViewReductionKind):
            return value
        return ViewReductionKind(value)

    @staticmethod
    def _coerce_summary_kind(value: ViewSummaryKind | str) -> ViewSummaryKind:
        if isinstance(value, ViewSummaryKind):
            return value
        return ViewSummaryKind(value)

    @staticmethod
    def _default_selectors(
        primitive_family: PrimitiveFamily,
    ) -> tuple[ViewSelectorKind, ...]:
        if primitive_family is PrimitiveFamily.ACCEPTED_OBSERVED_PATHS:
            return (
                ViewSelectorKind.ALL_ACCEPTED,
                ViewSelectorKind.BROAD_ENSEMBLE,
                ViewSelectorKind.EXACT_RANK_FIBER,
            )
        raise ValueError(
            f"unsupported primitive family: {primitive_family.value!r}"
        )

    @staticmethod
    def _default_summaries() -> tuple[ViewSummaryKind, ...]:
        return (
            ViewSummaryKind.SCALAR_INTERVAL_BINS,
            ViewSummaryKind.FAMILY_PARTITIONED_NU_E,
            ViewSummaryKind.TAIL_OPERATOR,
            ViewSummaryKind.UPWARD_CUT_OPERATOR,
            ViewSummaryKind.CUT_PROFILE_OPERATOR,
        )

    def to_contract_dict(self) -> dict[str, Any]:
        """Stable, shallow contract description for provenance/tests."""
        return {
            "view_id": self.view_id,
            "primitive_family": self.primitive_family.value,
            "predicate_context_present": self.predicate_context is not None,
            "observation_semantics_id": (
                self.observation_semantics.observation_semantics_id
            ),
            "time_weight_policy": self.time_weight_policy.version,
            "allowed_selectors": tuple(
                item.value for item in self.selectors()
            ),
            "allowed_summaries": tuple(
                item.value for item in self.summaries()
            ),
            "allowed_reductions": tuple(
                item.value for item in self.reductions()
            ),
        }


__all__ = [
    "OBSERVED_PATH_SEMANTICS_V1",
    "STANDARD_REDUCTION_VIEW_V1",
    "ObservationSemantics",
    "PrimitiveFamily",
    "ViewCtx",
    "ViewReductionKind",
    "ViewSelector",
    "ViewSelectorKind",
    "ViewSummaryKind",
]
